In [78]:
import numpy as np
# numpy 是pandas的基础，功能强大，运算快

In [4]:
import numpy as np
list1=[1,2,3]
print(type(list1))
print(list1)


<class 'list'>
[1, 2, 3]


In [5]:
arr1=np.array(list1)
print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[1 2 3]


In [9]:
arr2=np.array(object=[1,2,3])#命名传参
arr2

array([1, 2, 3])

In [10]:
arr3=np.array([[1,2,3],[4,5,6]])#位置传递传参
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr4=np.array([1,2,3],dtype=float)
arr4

array([1., 2., 3.])

In [21]:
arr5 = np.array([1.1,2.1,3.1],dtype=int,ndmin=0)
print(arr5)
arr6 = np.array([1.1,2.1,3.1],dtype=int,ndmin=1)
print(arr6)
arr7 = np.array([1.1,2.1,3.1],dtype=int,ndmin=2)#创建二维数组
print(arr7)
arr8 = np.array([1.1,2.1,3.1],dtype=int,ndmin=3)#创建三维数组
print(arr8)

[1 2 3]
[1 2 3]
[[1 2 3]]
[[[1 2 3]]]


In [23]:
arr9 =np.array(arr7)
arr7[0][1]=0
arr9

array([[1, 2, 3]])

In [27]:
arr10 =np.array(arr8,copy=False)
arr8[0][0][2]=4
print(arr10)
print(arr8)

[[[1 2 4]]]
[[[1 2 4]]]


In [29]:
#np.arange(start,stop,step,dtype)
#start起始值默认为0；stop终止值（不包含）；step步长（默认为1），dtype返回ndarray的数据类型（没有，则返回输入的类型）
a1=np.arange(0,6,1,dtype=int)
a1

array([0, 1, 2, 3, 4, 5])

In [37]:
#使用random创建随机数数组
ar = np.random.random(size=3)#创建3个0到1的浮点数（包前不包后，不会产生1，但能产生0）
ar

array([0.11602019, 0.56728562, 0.88527707])

In [36]:
ar1 = np.random.random(size=(2,3))#创建两行三列随机数数组
print(ar1)
print((ar1*10).astype(int))#设定类型为int，范围为1到10

[[0.77803994 0.22296891 0.00262313]
 [0.32913817 0.57224986 0.55562607]]
[[7 2 0]
 [3 5 5]]


In [43]:
#生成指定范围的整数随机数数组
ar2 = np.random.randint(1,4,6)#生成6个1到3的随机数
ar2

array([1, 3, 2, 3, 1, 3])

In [108]:
#随机数种子seed,为0则每次运行随机数不变
np.random.seed(5)
print(np.random.randint(1,6,2))
print(np.random.random(size=8))

# np.random.seed(0)
# print(np.random.randint(1,4,2))


[4 1]
[0.979445   0.08982104 0.39673661 0.35413804 0.486638   0.99082093
 0.80828168 0.64945888]


In [109]:
a1 = np.random.randint(1,10,5)
a2 = np.random.randint(1,10,size=(2,3))
print(a1.shape)#形状
print(a2.shape)#形状

print(a1.size)#大小
print(a1.dtype)#类型
print(a1.ndim)#几维数组

(5,)
(2, 3)
5
int32
1


In [121]:
#切片
np.random.seed(0)
a3 = np.random.randint(1,8,8)
print(a3)
print(a3[:])
print(a3[1:4])
print(a3[0::2])#起始终点步长


[5 6 1 4 4 4 2 4]
[5 6 1 4 4 4 2 4]
[6 1 4]
[5 1 4 2]


In [124]:
np.random.seed(0)
a4 = np.random.randint(1,8,size=(2,3))
print(a4)
a4[0][2]=1000
print(a4)


[[5 6 1]
 [4 4 4]]
[[   5    6 1000]
 [   4    4    4]]


In [135]:
#对数组进行升维和降维
num = np.arange(24)
print(num)
num1 = num.reshape(2,3,4)#需要计算

# reshape的三个参数：
# 第一个：将大盒子分成2块
# 第二个：将每一块分成三份
# 第三个：每一份有4个
# （需要计算，不能随便写）

print(num1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [134]:
#降维操作
num2 = num1.reshape(-1)
print(num2)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [147]:
#数组的拼接
x1 = np.arange(3)
y1 = np.arange(3,6)
print(np.concatenate([x1,y1]))
print("--------------")
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[10,20,30],[40,50,60]])
print(x)
print(y)
print(np.concatenate([x,y]))#直接竖向拼接
print(np.concatenate([x,y],axis=1))#横向拼接
print("--------------")
print(np.vstack([x,y]))#直接竖向拼接
print(np.hstack([x,y]))#横向拼接

[0 1 2 3 4 5]
--------------
[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]
--------------
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


In [152]:
#数组转置 行变成列列变成行
a = np.arange(1,13).reshape(2,6)
print(a)
print(a.T)
print(a.transpose())

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [170]:
#数组切割 split  axis=1(竖切) axis=0(横切)
#一维数组分割
z = np.arange(1,10)
print(z)
z1 = np.split(z,3)
print(z1)
print("-------------------")
z2 = np.arange(16).reshape(4,4)
print(z2)
z3 = np.split(z2,2)
print(z3)
print("-------------------")
z4 = np.split(z2,2,axis=1)
print(z4)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
-------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
-------------------
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [16]:
import numpy as np
#数学函数
# + - * \ % **
a = np.arange(9,dtype=np.float64).reshape(3,3)
print(a)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
d = np.array([[1,2,3],[4,5,6]])
print(b)
print(c)
print(d)
print("---------------------")
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b) #幂运算
print("---------------------")

print(a+c)
print(a-c)
print(a*c)
print(a/c)
print(a%c)
print(a**c) #幂运算
print("---------------------")

#(3,3)的数组不能和(2,3)的数组一起运算
# print(a+d)
# print(a-d)
# print(a*d)
# print(a/d)
# print(a%d)
# print(a**d) #幂运算


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
---------------------
[[ 1.  3.  5.]
 [ 4.  6.  8.]
 [ 7.  9. 11.]]
[[-1. -1. -1.]
 [ 2.  2.  2.]
 [ 5.  5.  5.]]
[[ 0.  2.  6.]
 [ 3.  8. 15.]
 [ 6. 14. 24.]]
[[0.         0.5        0.66666667]
 [3.         2.         1.66666667]
 [6.         3.5        2.66666667]]
[[0. 1. 2.]
 [0. 0. 2.]
 [0. 1. 2.]]
[[  0.   1.   8.]
 [  3.  16. 125.]
 [  6.  49. 512.]]
---------------------
[[ 1.  3.  5.]
 [ 7.  9. 11.]
 [13. 15. 17.]]
[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]
[[ 0.  2.  6.]
 [12. 20. 30.]
 [42. 56. 72.]]
[[0.         0.5        0.66666667]
 [0.75       0.8        0.83333333]
 [0.85714286 0.875      0.88888889]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[0.00000000e+00 1.00000000e+00 8.00000000e+00]
 [8.10000000e+01 1.02400000e+03 1.56250000e+04]
 [2.79936000e+05 5.76480100e+06 1.34217728e+08]]
---------------------


In [21]:
#平方和和开平方
a = np.arange(1,10,dtype=np.float64).reshape(3,3)
print(a)
print(np.square(a))
print(np.sqrt(a))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [27]:
#对小数的处理
#四舍五入
# 天花板
# 地板
a = np.array([1.0,4.55,123.0,0.567,25.532])
print('四舍五入，保留两位小数',np.around(a,2))
print("四舍五入",np.around(a))
print("向上取整（天花板）",np.ceil(a))
print("向下取整（地板）",np.floor(a))



四舍五入，保留两位小数 [  1.     4.55 123.     0.57  25.53]
四舍五入 [  1.   5. 123.   1.  26.]
向上取整（天花板） [  1.   5. 123.   1.  26.]
向下取整（地板） [  1.   4. 123.   0.  25.]


In [55]:
#统计函数
# SQL
# 最大值，最小值，平均数，求和，中位数，计数，标准差，方差


#最小值
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
#求全部数组的最小值
#还是按行或者按列来求
print("------最小值--------")
print(a)
print(a.min())
print(np.min(a))
print(np.min(a,axis=1))#按行来求最小值
print(np.min(a,axis=0))#按列来求最小值
print("------最大值--------")
print(a.max())
print(np.max(a))
print(np.max(a,axis=1))#按行来求最大值
print(np.max(a,axis=0))#按列来求最大值
print("------中位数--------")
b = np.array([1000,2000,3000,40000,50000,100000,20000,9999999999])
print(b)
print(np.percentile(b,50))
print(np.percentile(b,20))
print(np.percentile(b,75))
print("------求和--------")
print(b.sum())
print(a.sum())
print("------计数--------")
c = np.array([[1,2,3],[4,5,6]])
print(len(a))#len()这个算法用在多维数组和size有区别的
print(len(c))
print(len(b))
print(a.size)#这种方法可以算多维数组总共有多少个数
print(b.size)

print("-------标准差（数据的离散程度）--------")
s = np.array([80,81,82,79,80])
print(s)
print(np.mean(s))#求平均数
print(s - np.mean(s))#求方差
print(np.sqrt(np.mean((s - np.mean(s))**2)))#得到标准差
print(np.std(s))#直接使用函数
#得到的数据越小表明这组数据离散程度越低


------最小值--------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
1
[1 4 7]
[1 2 3]
------最大值--------
9
9
[3 6 9]
[7 8 9]
------中位数--------
[      1000       2000       3000      40000      50000     100000
      20000 9999999999]
30000.0
2400.0
62500.0
------求和--------
10000215999
45
------计数--------
3
2
8
9
8
-------标准差（数据的离散程度）--------
[80 81 82 79 80]
80.4
[-0.4  0.6  1.6 -1.4 -0.4]
1.019803902718557
1.019803902718557


In [61]:
#numpy广播机制 ：解决不同形状数组之间的算术运算问题（对数组进行水平或垂直方向的拉伸）
a = np.array([0,1,2])
print(a)
print(a+5)# 实际是把实数5拉长成了[5,5,5]
a = np.array([[0,0,0],[1,2,3],[10,20,30]])
b = np.array([1,2,3])#实际是把[1,2,3]拉长成了[[1,2,3],[1,2,3],[1,2,3]]
print(a+b) 

[0 1 2]
[5 6 7]
[[ 1  2  3]
 [ 2  4  6]
 [11 22 33]]


In [63]:
#排序
a = np.array([5,10,30,50,88,20])
np.sort(a)

array([ 5, 10, 20, 30, 50, 88])

In [68]:
#比较掩码
a = np.array([[1,2,30],[45,67,88]])
print(a)
print(a<60)
print(a[a<60])

[[ 1  2 30]
 [45 67 88]]
[[ True  True  True]
 [ True False False]]
[ 1  2 30 45]


In [76]:
#索引
print(a[:])
print(a[:2])
print(a[1:])
print(a[1:2])
print(a[:,0])#拿到的是第一列
print(a[:,1])#拿到的是第二列
print(a[:,2])#拿到的是第三列

[[ 1  2 30]
 [45 67 88]]
[[ 1  2 30]
 [45 67 88]]
[[45 67 88]]
[[45 67 88]]
[ 1 45]
[ 2 67]
[30 88]
