In [1]:
import numpy as np


In [4]:
import numpy as np
list1=[1,2,3]
print(type(list1))
print(list1)


<class 'list'>
[1, 2, 3]


In [5]:
arr1=np.array(list1)
print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[1 2 3]


In [9]:
arr2=np.array(object=[1,2,3])#命名传参
arr2

array([1, 2, 3])

In [10]:
arr3=np.array([[1,2,3],[4,5,6]])#位置传递传参
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr4=np.array([1,2,3],dtype=float)
arr4

array([1., 2., 3.])

In [21]:
arr5 = np.array([1.1,2.1,3.1],dtype=int,ndmin=0)
print(arr5)
arr6 = np.array([1.1,2.1,3.1],dtype=int,ndmin=1)
print(arr6)
arr7 = np.array([1.1,2.1,3.1],dtype=int,ndmin=2)#创建二维数组
print(arr7)
arr8 = np.array([1.1,2.1,3.1],dtype=int,ndmin=3)#创建三维数组
print(arr8)

[1 2 3]
[1 2 3]
[[1 2 3]]
[[[1 2 3]]]


In [23]:
arr9 =np.array(arr7)
arr7[0][1]=0
arr9

array([[1, 2, 3]])

In [27]:
arr10 =np.array(arr8,copy=False)
arr8[0][0][2]=4
print(arr10)
print(arr8)

[[[1 2 4]]]
[[[1 2 4]]]


In [29]:
#np.arange(start,stop,step,dtype)
#start起始值默认为0；stop终止值（不包含）；step步长（默认为1），dtype返回ndarray的数据类型（没有，则返回输入的类型）
a1=np.arange(0,6,1,dtype=int)
a1

array([0, 1, 2, 3, 4, 5])

In [37]:
#使用random创建随机数数组
ar = np.random.random(size=3)#创建3个0到1的浮点数（包前不包后，不会产生1，但能产生0）
ar

array([0.11602019, 0.56728562, 0.88527707])

In [36]:
ar1 = np.random.random(size=(2,3))#创建两行三列随机数数组
print(ar1)
print((ar1*10).astype(int))#设定类型为int，范围为1到10

[[0.77803994 0.22296891 0.00262313]
 [0.32913817 0.57224986 0.55562607]]
[[7 2 0]
 [3 5 5]]


In [43]:
#生成指定范围的整数随机数数组
ar2 = np.random.randint(1,4,6)#生成6个1到3的随机数
ar2

array([1, 3, 2, 3, 1, 3])

In [108]:
#随机数种子seed,为0则每次运行随机数不变
np.random.seed(5)
print(np.random.randint(1,6,2))
print(np.random.random(size=8))

# np.random.seed(0)
# print(np.random.randint(1,4,2))


[4 1]
[0.979445   0.08982104 0.39673661 0.35413804 0.486638   0.99082093
 0.80828168 0.64945888]


In [109]:
a1 = np.random.randint(1,10,5)
a2 = np.random.randint(1,10,size=(2,3))
print(a1.shape)#形状
print(a2.shape)#形状

print(a1.size)#大小
print(a1.dtype)#类型
print(a1.ndim)#几维数组

(5,)
(2, 3)
5
int32
1


In [121]:
#切片
np.random.seed(0)
a3 = np.random.randint(1,8,8)
print(a3)
print(a3[:])
print(a3[1:4])
print(a3[0::2])#起始终点步长


[5 6 1 4 4 4 2 4]
[5 6 1 4 4 4 2 4]
[6 1 4]
[5 1 4 2]


In [124]:
np.random.seed(0)
a4 = np.random.randint(1,8,size=(2,3))
print(a4)
a4[0][2]=1000
print(a4)


[[5 6 1]
 [4 4 4]]
[[   5    6 1000]
 [   4    4    4]]


In [135]:
#对数组进行升维和降维
num = np.arange(24)
print(num)
num1 = num.reshape(2,3,4)#需要计算

# reshape的三个参数：
# 第一个：将大盒子分成2块
# 第二个：将每一块分成三份
# 第三个：每一份有4个
# （需要计算，不能随便写）

print(num1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [134]:
#降维操作
num2 = num1.reshape(-1)
print(num2)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [147]:
#数组的拼接
x1 = np.arange(3)
y1 = np.arange(3,6)
print(np.concatenate([x1,y1]))
print("--------------")
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[10,20,30],[40,50,60]])
print(x)
print(y)
print(np.concatenate([x,y]))#直接竖向拼接
print(np.concatenate([x,y],axis=1))#横向拼接
print("--------------")
print(np.vstack([x,y]))#直接竖向拼接
print(np.hstack([x,y]))#横向拼接

[0 1 2 3 4 5]
--------------
[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]
--------------
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


In [152]:
#数组转置 行变成列列变成行
a = np.arange(1,13).reshape(2,6)
print(a)
print(a.T)
print(a.transpose())

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [170]:
#数组切割 split  axis=1(竖切) axis=0(横切)
#一维数组分割
z = np.arange(1,10)
print(z)
z1 = np.split(z,3)
print(z1)
print("-------------------")
z2 = np.arange(16).reshape(4,4)
print(z2)
z3 = np.split(z2,2)
print(z3)
print("-------------------")
z4 = np.split(z2,2,axis=1)
print(z4)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
-------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
-------------------
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
