In [41]:
import numpy as np
#1.案例背景:分析学生成绩数据
# 假设我们有一份学生成绩数据，包含学生的学号、语文成绩、数学成绩和英语成绩。
# 我们的目标是通过numpy进行数据分析，包括计算平均分、最高分、最低分、成绩的标准差等统计指标，以及对成绩进行排序和筛选。
# 首先，我们创建一个numpy数组来存储学生成绩数据。为了方便演示，我们手动创建一个小型的数据集。
#学生成绩数据，每一行代表一个学生列分别是学号语文数学英语成绩
data = np.array([[1,80,75,90],[2,90,85,88],[3,70,75,78],[4,85,80,95],[5,95,90,85]])
#1.计算各科平均分
#2.计算各科的最高分和最低分
# 3.按照总分对学生进行排序
# 4.筛选出数学成绩大于80分的学生
print(data)
print("------第一题-------")
a1 = np.mean(data[:,1])
# a = data[:,1].mean()
print("语文平均分：",a1)
a2 = np.mean(data[:,2])
# a = data[:,2].mean()
print("数学平均分：",a2)
a3 = np.mean(data[:,3])
# a = data[:,1].mean()
print("英语平均分：",a3)
print("------第二题-------")
b1 = np.max(data[:,1])
print("语文最高分：",b1)
b2 = np.max(data[:,2])
print("数学最高分：",b2)
b3 = np.max(data[:,3])
print("英语最高分：",b3)
b4 = np.min(data[:,1])
print("语文最低分：",b4)
b5 = np.min(data[:,2])
print("数学最低分：",b5)
b6 = np.min(data[:,3])
print("英语最低分：",b6)
print("------第三题-------")
c1 = np.sum(data[:,1])
c2 = np.sum(data[:,2])
c3 = np.sum(data[:,3])
print("总分从低到高：",np.sort([c1,c2,c3]))
print("总分从高到低：",np.sort([c1,c2,c3])[::-1])#逆序
print("------第四题-------")
print(data[data[:,2]>80])

[[ 1 80 75 90]
 [ 2 90 85 88]
 [ 3 70 75 78]
 [ 4 85 80 95]
 [ 5 95 90 85]]
------第一题-------
语文平均分： 84.0
数学平均分： 81.0
英语平均分： 87.2
------第二题-------
语文最高分： 95
数学最高分： 90
英语最高分： 95
语文最低分： 70
数学最低分： 75
英语最低分： 78
------第三题-------
总分从低到高： [405 420 436]
总分从高到低： [436 420 405]
------第四题-------
[[ 2 90 85 88]
 [ 5 95 90 85]]
